# Goal - where to go
float32[3] target_position
float32 yaw
---
# Result - did we make it?
bool success
string message  # "Reached waypoint" or "Cancelled due to obstacle"
---
# Feedback - progress updates
float32 distance_remaining
geometry_msgs/PoseStamped current_pose