# Goal - where to go
uav_interfaces/Waypoint target_waypoint
---
# Result - did we make it?
bool success
string message  # "Reached waypoint" or "Cancelled due to obstacle"
---
# Feedback - progress updates
float32 distance_remaining
uav_interfaces/Waypoint current_pose